In [5]:
import pandas as pd

In [10]:
df=pd.read_csv("/content/raw_data/gsearch_jobs.csv")
df.head()

,Unnamed: 0,index,title,company_name,location,via,description,extensions,job_id,thumbnail,...,commute_time,salary_pay,salary_rate,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized,description_tokens
0,0,0,Data Analyst,Meta,Anywhere,via LinkedIn,In the intersection of compliance and analytic...,"['15 hours ago', '101K–143K a year', 'Work fro...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,https://encrypted-tbn0.gstatic.com/images?q=tb...,...,NaN,101K–143K,a year,122000.0,101000.0,143000.0,NaN,122000.0,122000.0,"['tableau', 'r', 'python', 'sql']"
1,1,1,Data Analyst,ATC,United States,via LinkedIn,Job Title: Entry Level Business Analyst / Prod...,"['12 hours ago', 'Full-time', 'Health insurance']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,https://encrypted-tbn0.gstatic.com/images?q=tb...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[]
2,2,2,Aeronautical Data Analyst,"Garmin International, Inc.","Olathe, KS",via Indeed,Overview:\n\nWe are seeking a full-time...\nAe...,"['18 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJBZXJvbmF1dGljYWwgRGF0YSBBbm...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['sql']
3,3,3,Data Analyst - Consumer Goods - Contract to Hire,Upwork,Anywhere,via Upwork,Enthusiastic Data Analyst for processing sales...,"['12 hours ago', '15–25 an hour', 'Work from h...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgLSBDb25zdW...,NaN,...,NaN,15–25,an hour,20.0,15.0,25.0,20.0,NaN,41600.0,"['powerpoint', 'excel', 'power_bi']"
4,4,4,Data Analyst | Workforce Management,Krispy Kreme,United States,via LinkedIn,Overview of Position\n\nThis position will be ...,"['7 hours ago', '90K–110K a year', 'Contractor']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgfCBXb3JrZm...,https://encrypted-tbn0.gstatic.com/images?q=tb...,...,NaN,90K–110K,a year,100000.0,90000.0,110000.0,NaN,100000.0,100000.0,"['powerpoint', 'excel', 'outlook', 'word']"

In [17]:
df.tail()

,Unnamed: 0,index,title,company_name,location,via,description,extensions,job_id,thumbnail,...,commute_time,salary_pay,salary_rate,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized,description_tokens
61948,61948,955,Marketing Data & BI Analyst II,EDWARD JONES,"Houstonia, MO",via My ArkLaMiss Jobs,"At Edward Jones, we help clients achieve their...","['23 hours ago', '76,798–130,764 a year', 'Ful...",eyJqb2JfdGl0bGUiOiJNYXJrZXRpbmcgRGF0YSBcdTAwMj...,NaN,...,NaN,76798–130764,a year,103781.0,76798.0,130764.0,NaN,103781.0,103781.0,"['power_bi', 'tableau', 'excel', 'snowflake', ..."
61949,61949,956,Lead-Data Analyst,EDWARD JONES,"Marshfield, MO",via My ArkLaMiss Jobs,"At Edward Jones, we help clients achieve their...","['23 hours ago', '106,916–182,047 a year', 'Fu...",eyJqb2JfdGl0bGUiOiJMZWFkLURhdGEgQW5hbHlzdCIsIm...,NaN,...,NaN,106916–182047,a year,144481.5,106916.0,182047.0,NaN,144481.5,144481.5,[]
61950,61950,957,Lead-Data Analyst,EDWARD JONES,"High Point, MO",via My ArkLaMiss Jobs,"At Edward Jones, we help clients achieve their...","['23 hours ago', '106,916–182,047 a year', 'Fu...",eyJqb2JfdGl0bGUiOiJMZWFkLURhdGEgQW5hbHlzdCIsIm...,NaN,...,NaN,106916–182047,a year,144481.5,106916.0,182047.0,NaN,144481.5,144481.5,[]
61951,61951,958,Lead-Data Analyst,EDWARD JONES,"Calhoun, MO",via My ArkLaMiss Jobs,"At Edward Jones, we help clients achieve their...","['23 hours ago', '106,916–182,047 a year', 'Fu...",eyJqb2JfdGl0bGUiOiJMZWFkLURhdGEgQW5hbHlzdCIsIm...,NaN,...,NaN,106916–182047,a year,144481.5,106916.0,182047.0,NaN,144481.5,144481.5,[]
61952,61952,959,Institutional Credit Management - Lending Data...,Citi,United States,via My ArkLaMiss Jobs,The Institutional Credit Management (ICM) grou...,"['24 hours ago', '105,850–158,780 a year', 'Fu...",eyJqb2JfdGl0bGUiOiJJbnN0aXR1dGlvbmFsIENyZWRpdC...,https://encrypted-tbn0.gstatic.com/images?q=tb...,...,NaN,105850–158780,a year,132315.0,105850.0,158780.0,NaN,132315.0,132315.0,"['tableau', 'cognos']"

In [19]:
df.sample(5)

,Unnamed: 0,index,title,company_name,location,via,description,extensions,job_id,thumbnail,...,commute_time,salary_pay,salary_rate,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized,description_tokens
32059,32059,16,Business Intelligence,Seacoast National Bank,"Wichita, KS",via BeBee,The Business Intelligence Manager (BI Manager)...,"['14 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJCdXNpbmVzcyBJbnRlbGxpZ2VuY2...,https://encrypted-tbn0.gstatic.com/images?q=tb...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['power_bi', 'c', 'sas', 'sql', 'mysql', 'visio']"
31535,31535,1887,Senior Data Analyst,Continental Resources,"Del City, OK",via BeBee,Job Summary\n\nThe Senior Data Analyst is prim...,"['8 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJTZW5pb3IgRGF0YSBBbmFseXN0Ii...,https://encrypted-tbn0.gstatic.com/images?q=tb...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['sap', 'sql', 'r', 'python', 'alteryx']"
20347,20347,187,Complaints Data Analyst,JPMorgan Chase & Co.,United States,via Trabajo.org,The Complaints team is a new arm of the Data &...,"['23 hours ago', 'Full-time', 'No degree menti...",eyJqb2JfdGl0bGUiOiJDb21wbGFpbnRzIERhdGEgQW5hbH...,https://encrypted-tbn0.gstatic.com/images?q=tb...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['r']
29562,29562,2535,"United States (Remote) Senior Data Analyst, Ma...",vmysmartpros,Anywhere,Mysmartpros,"United States (Remote) Senior Data Analyst, Ma...","['14 hours ago', 'Work from home', 'Full-time'...",eyJqb2JfdGl0bGUiOiJVbml0ZWQgU3RhdGVzIChSZW1vdG...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['tableau', 'looker', 'sql']"
24074,24074,1337,Data Scientist II,ClassPass,Anywhere,via LinkedIn,We're revolutionizing the fitness & wellness i...,"['15 hours ago', 'Work from home', 'Full-time'...",eyJqb2JfdGl0bGUiOiJEYXRhIFNjaWVudGlzdCBJSSIsIm...,https://encrypted-tbn0.gstatic.com/images?q=tb...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['tableau', 'aws', 'looker', 'sql', 'r', 'pyth..."

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61953 entries, 0 to 61952
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           61953 non-null  int64
 1   index                61953 non-null  int64
 2   title                61953 non-null  object
 3   company_name         61953 non-null  object
 4   location             61916 non-null  object
 5   via                  61944 non-null  object
 6   description          61953 non-null  object
 7   extensions           61953 non-null  object
 8   job_id               61953 non-null  object
 9   thumbnail            38194 non-null  object
 10  posted_at            61763 non-null  object
 11  schedule_type        61707 non-null  object
 12  work_from_home       27980 non-null  object
 13  salary               10088 non-null  object
 14  search_term          61953 non-null  object
 15  date_time            61953 non-null  object
 16  search_location      61953 non-null  object
 17  commute_time         0 non-null      float64
 18  salary_pay           10088 non-null  object
 19  salary_rate          10088 non-null  object
 20  salary_avg           10088 non-null  float64
 21  salary_min           9512 non-null   float64
 22  salary_max           9512 non-null   float64
 23  salary_hourly        5900 non-null   float64
 24  salary_yearly        4069 non-null   float64
 25  salary_standardized  10088 non-null  float64
 26  description_tokens   61953 non-null  object
dtypes: float64(7), int64(2), object(18)
memory usage: 12.8+ MB

In [21]:
print("No.of rows :",df.shape[0])
print("No.of columns :",df.shape[1])
print("No.of numeric columns :",df.select_dtypes(include='number').shape[1])
print("No.of object columns :",df.select_dtypes(include='object').shape[1])

No.of rows : 61953
No.of columns : 27
No.of numeric columns : 9
No.of object columns : 18

In [20]:
df.describe()

,Unnamed: 0,index,commute_time,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized
count,61953.000000,61953.000000,0.0,10088.000000,9512.000000,9512.000000,5900.000000,4069.000000,10088.000000
mean,30976.000000,1139.077333,NaN,42100.231239,34846.281874,50487.856787,40.539588,104115.406718,92289.425683
std,17884.434951,690.256113,NaN,55893.993519,45843.034891,67366.522273,22.214540,36024.388492,43277.933820
min,0.000000,0.000000,NaN,7.250000,8.000000,10.000000,7.250000,29289.840000,15080.000000
25%,15488.000000,553.000000,NaN,31.500000,19.520000,45.000000,23.265000,80000.180000,62400.000000
50%,30976.000000,1111.000000,NaN,60.000000,50.000000,75.000000,33.500000,96500.000000,88400.000000
75%,46464.000000,1685.000000,NaN,92500.000000,77000.000000,110000.000000,55.000000,120000.000000,117500.000000
max,61952.000000,3228.000000,NaN,550000.000000,450000.000000,850000.000000,300.000000,550000.000000,624000.000000

In [26]:
df.isnull().sum()

Unnamed: 0                 0
index                      0
title                      0
company_name               0
location                  37
via                        9
description                0
extensions                 0
job_id                     0
thumbnail              23759
posted_at                190
schedule_type            246
work_from_home         33973
salary                 51865
search_term                0
date_time                  0
search_location            0
commute_time           61953
salary_pay             51865
salary_rate            51865
salary_avg             51865
salary_min             52441
salary_max             52441
salary_hourly          56053
salary_yearly          57884
salary_standardized    51865
description_tokens         0
dtype: int64

In [27]:
print("Most null columns :",df.isnull().sum().idxmax())

Most null columns : commute_time

In [28]:
print("Minimum null columns :",df.isnull().sum().idxmin())

Most null columns : Unnamed: 0

In [37]:
snc=(df.isnull().sum() > 0).sum()
print("Sum of null columns :",snc)

Sum of null columns : 16

In [47]:
dr=df.duplicated().sum()
print("Sum of duplicate rows :",dr)

Sum of duplicate rows : 0

In [63]:
print("Common job role :",df['title'].value_counts().idxmax()," and Job-avialabe :",df['title'].value_counts().max())

Common job role : Data Analyst  and Job-avialabe : 6444

In [80]:
print("Unique-roles :",df['title'].value_counts().unique().sum())

Unique-roles : 18201

In [68]:
print("Common job location:",df['location'].value_counts().idxmax())

Common job location:  Anywhere

In [81]:
print("Unique-location :",df['location'].value_counts().unique().sum())

Unique-location : 56576

In [82]:
print("Common job sources:",df['via'].value_counts().idxmax())

Common job sources: via LinkedIn

In [83]:
print("Unique-job_sources :",df['via'].value_counts().unique().sum())

Unique-job_sources : 57632

In [84]:
print("Common job schedule_type:",df['schedule_type'].value_counts().idxmax())

Common job schedule_type: Full-time

In [89]:
print("Unique-job_schedule_type:",df['schedule_type'].value_counts().unique().sum())

Unique-job_schedule_type: 61672

In [93]:
 print("No.job avilable for work_from_home :",df['work_from_home'].value_counts().max())

No.job avilable for work_from_home : 27980

In [98]:
df['work_from_home'].count()

np.int64(27980)

In [99]:
salary=df['salary_avg']

In [101]:
salary.describe()

count     10088.000000
mean      42100.231239
std       55893.993519
min           7.250000
25%          31.500000
50%          60.000000
75%       92500.000000
max      550000.000000
Name: salary_avg, dtype: float64

In [102]:
salary.median()

60.0

In [116]:
df.groupby('salary')['title'].value_counts()

salary             title
1.8K–2.4K a month  Finance Data Analyst                                                                                  1
10 an hour         Data Analyst                                                                                          2
                   Data Analyst - Contract to Hire                                                                       1
                   Expert Questionnaire Writer data collector, data analyst and lead generator, in arabic and english    1
                   Financial & data analyst guru - Contract to hire                                                      1
                                                                                                                        ..
9–18 an hour       Data analyst                                                                                          1
9–25 an hour       Statistical analysis for education research data                                                      1
9–30 an hour       Data Analyst for Sales, Marketing, Research, and Call Center Data                                     1
9–37 an hour       Create basic algorithm based on backtesting data                                                      1
9–50 an hour       Mobile App Data Analyst                                                                               1
Name: count, Length: 6824, dtype: int64

TOP 5 OBSERVATIONS

1. Data Analyst is the most frequently occurring job title in the dataset.
2. **Missing Data:** A significant number of columns have missing values; notably, the 'commute_time' column is entirely null, and salary-related fields also have many missing entries.
3. **No Duplicate Records:** The dataset does not contain any duplicate rows, ensuring data uniqueness.
4. **Flexible Work Locations:** 'Anywhere' is the most common job location, suggesting a high availability of remote or location-agnostic roles.
5. **Predominant Job Characteristics:** 'Full-time' is the most frequent job schedule type, and 'via LinkedIn' is the most common source for job postings.