In [2]:
import sqlite3
import pandas as pd

df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Minor Project/job_market_cleaned.csv')
df['via'] = df['via'].str.replace('via ', '', regex=False)
conn = sqlite3.connect("job_market_cleaned.db")

In [3]:
df.to_sql(
    "jobs",
    conn,
    if_exists="replace",
    index=False
)

61953

In [ ]:
pd.read_sql_query("SELECT * FROM jobs LIMIT 5;", conn)

,Unnamed: 0,index,title,company_name,location,via,description,extensions,job_id,posted_at,...,salary_rate,salary_avg,salary_min,salary_max,salary_hourly,salary_yearly,salary_standardized,description_tokens,Posted_Year,Posted_Month
0,0,0,Data Analyst,Meta,Anywhere,LinkedIn,In the intersection of compliance and analytic...,"['15 hours ago', '101K–143K a year', 'Work fro...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,2023-08-03 12:00:13.797776,...,a year,122000.0,101000.0,143000.0,NaN,122000.0,122000.0,"['tableau', 'r', 'python', 'sql']",2023.0,8.0
1,1,1,Data Analyst,ATC,United States,LinkedIn,Job Title: Entry Level Business Analyst / Prod...,"['12 hours ago', 'Full-time', 'Health insurance']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QiLCJodGlkb2...,2023-08-03 15:00:13.797776,...,None,NaN,NaN,NaN,NaN,NaN,NaN,[],2023.0,8.0
2,2,2,Aeronautical Data Analyst,"Garmin International, Inc.","Olathe, KS",Indeed,Overview:\n\nWe are seeking a full-time...\nAe...,"['18 hours ago', 'Full-time']",eyJqb2JfdGl0bGUiOiJBZXJvbmF1dGljYWwgRGF0YSBBbm...,2023-08-03 09:00:13.797776,...,None,NaN,NaN,NaN,NaN,NaN,NaN,['sql'],2023.0,8.0
3,3,3,Data Analyst - Consumer Goods - Contract to Hire,Upwork,Anywhere,Upwork,Enthusiastic Data Analyst for processing sales...,"['12 hours ago', '15–25 an hour', 'Work from h...",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgLSBDb25zdW...,2023-08-03 15:00:13.797776,...,an hour,20.0,15.0,25.0,20.0,NaN,41600.0,"['powerpoint', 'excel', 'power_bi']",2023.0,8.0
4,4,4,Data Analyst | Workforce Management,Krispy Kreme,United States,LinkedIn,Overview of Position\n\nThis position will be ...,"['7 hours ago', '90K–110K a year', 'Contractor']",eyJqb2JfdGl0bGUiOiJEYXRhIEFuYWx5c3QgfCBXb3JrZm...,2023-08-03 20:00:13.797776,...,a year,100000.0,90000.0,110000.0,NaN,100000.0,100000.0,"['powerpoint', 'excel', 'outlook', 'word']",2023.0,8.0

SQL_ANALYSIS

1.Total job postings

In [ ]:
pd.read_sql_query("Select Count(*) AS Total_Job_Postings  FROM jobs ",conn)

   Total_Job_Postings
0               61953

2.Top 5 Job Roles

In [ ]:
pd.read_sql_query(
'''SELECT title, COUNT(*) AS Job_Count
   FROM jobs
   GROUP BY title
   ORDER BY Job_Count DESC
   LIMIT 5; ''',conn)

                   title  Job_Count
0           Data Analyst       6444
1    Senior Data Analyst       1748
2         Data Scientist        931
3        Data Analyst II        644
4  Business Data Analyst        495

3.Top 5 Companies

In [ ]:
pd.read_sql_query(
'''SELECT company_name, COUNT(*) AS Job_Post_Count
   FROM jobs
   GROUP BY company_name
   ORDER BY Job_Post_Count DESC
   LIMIT 5; ''',conn)

   company_name  Job_Post_Count
0        Upwork            7533
1  Talentify.io            2118
2       Walmart            1829
3  vmysmartpros            1415
4          Dice             862

4.Top Job Sources

In [ ]:
pd.read_sql_query(
'''SELECT via, COUNT(*) AS Job_Post_Count
   FROM jobs
   GROUP BY via
   ORDER BY Job_Post_Count DESC
   LIMIT 5; ''',conn)

            via  Job_Post_Count
0      LinkedIn           22399
1         BeBee            8315
2        Upwork            7505
3  ZipRecruiter            3171
4   Trabajo.org            3117

5.Top 5 job schedule types by number of job postings?

In [ ]:
pd.read_sql_query(
'''SELECT  schedule_type, COUNT(*) AS Job_Post_Count
   FROM jobs
   GROUP BY  schedule_type
   ORDER BY Job_Post_Count DESC
   LIMIT 5; ''',conn)

              schedule_type  Job_Post_Count
0                 Full-time           45082
1                Contractor            9284
2  Contractor and Temp work            3130
3   Full-time and Part-time            1187
4                 Part-time            1144

6.How many jobs are marked as work-from-home/remote?

In [ ]:
pd.read_sql_query(
'''SELECT COUNT(*) AS Work_From_Home_Jobs
   FROM jobs
   WHERE work_from_home=1; ''',conn)

   Work_From_Home_Jobs
0                27980

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61953 entries, 0 to 61952
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           61953 non-null  int64
 1   index                61953 non-null  int64
 2   title                61953 non-null  object
 3   company_name         61953 non-null  object
 4   location             61916 non-null  object
 5   via                  61944 non-null  object
 6   description          61953 non-null  object
 7   extensions           61953 non-null  object
 8   job_id               61953 non-null  object
 9   posted_at            61763 non-null  object
 10  schedule_type        61707 non-null  object
 11  work_from_home       27980 non-null  object
 12  salary               10088 non-null  object
 13  search_term          61953 non-null  object
 14  date_time            61953 non-null  object
 15  search_location      61953 non-null  object
 16  salary_pay           10088 non-null  object
 17  salary_rate          10088 non-null  object
 18  salary_avg           10088 non-null  float64
 19  salary_min           9512 non-null   float64
 20  salary_max           9512 non-null   float64
 21  salary_hourly        5900 non-null   float64
 22  salary_yearly        4069 non-null   float64
 23  salary_standardized  10088 non-null  float64
 24  description_tokens   61953 non-null  object
 25  Posted_Year          61763 non-null  float64
 26  Posted_Month         61763 non-null  float64
dtypes: float64(8), int64(2), object(17)
memory usage: 12.8+ MB

7.Average Yearly Salary by Role

In [11]:
pd.read_sql_query(
'''SELECT title,AVG(salary_yearly) AS Avg_salary
   FROM jobs
   WHERE salary_yearly IS NOT NULL
   GROUP BY title
   HAVING COUNT(*) >= 10
   ORDER BY Avg_salary DESC
   LIMIT 10''',conn)

                                         title     Avg_salary
0                     Principal Data Scientist  198250.000000
1                            Lead-Data Analyst  144731.966667
2                               Data Scientist  128865.660377
3                                Data Engineer  127673.552632
4                          Data Analytics Lead  124703.000000
5  Senior Performance Marketing (Data Analyst)  122470.500000
6                            Lead Data Analyst  117626.500000
7                          Senior Data Analyst  116871.927774
8                             Sr. Data Analyst  104956.892857
9               Marketing Data & BI Analyst II  103781.000000

8.Job Postings by Month

In [15]:
pd.read_sql_query(
'''SELECT
    Posted_Month,
    COUNT(*) AS Job_Count
    FROM jobs
    WHERE Posted_Month IS NOT NULL
    GROUP BY  Posted_Month
    ORDER BY Posted_Month''',conn)

    Posted_Month  Job_Count
0            1.0       8006
1            2.0       7230
2            3.0       6474
3            4.0       5067
4            5.0       4120
5            6.0       3969
6            7.0       4002
7            8.0       3041
8            9.0       3507
9           10.0       4249
10          11.0       5430
11          12.0       6668

9.Demand vs Average Salary

In [19]:
pd.read_sql_query(
    '''
  SELECT title,
       COUNT(*) AS Job_count,
       AVG(salary_yearly) AS Avg_salary
FROM jobs
GROUP BY title
ORDER BY Job_count DESC
LIMIT 10;
''',conn
)

                           title  Job_count     Avg_salary
0                   Data Analyst       6444   88368.485124
1            Senior Data Analyst       1748  116871.927774
2                 Data Scientist        931  128865.660377
3                Data Analyst II        644   94210.724464
4          Business Data Analyst        495   86108.064516
5              Lead Data Analyst        428  117626.500000
6            Survey Data Analyst        422   53333.333333
7                  Data Engineer        375  127673.552632
8  Business Intelligence Analyst        343   86790.394737
9               Data Analyst III        284  108040.000000

10.Remote Jobs by Job Role

In [20]:
pd.read_sql_query(
    '''
    SELECT title, COUNT(work_from_home) AS Remote_Jobs
    FROM jobs
    WHERE work_from_home = 1
    GROUP BY title
    ORDER BY Remote_Jobs DESC
    LIMIT 10;
    ''',conn
)

                             title  Remote_Jobs
0                     Data Analyst         2145
1              Senior Data Analyst          660
2                   Data Scientist          640
3                    Data Engineer          259
4            Business Data Analyst          205
5    Business Intelligence Analyst          164
6           Marketing Data Analyst          114
7                 Business Analyst          113
8  Data Analyst - Contract to Hire           98
9                 Sr. Data Analyst           85